import type { MegaPasta, OmegaPasta } from "../../chat-pasta/utils/pasta";
import type { WithPastasIndexedDB } from "./pastas-db-types";

export class PastasListIndexedDBStore {
  constructor(private readonly withDatabase: WithPastasIndexedDB) {}

  put(pasta: OmegaPasta) {
    return this.withDatabase((database) => database.put("list", pasta));
  }

  getAll() {
    return this.withDatabase((database) => database.getAll("list"));
  }

  add(pasta: MegaPasta) {
    // @ts-expect-error ts(2345) id MUST be autogenerated by IndexedDB
    return this.withDatabase((database) => database.add("list", pasta));
  }
}
