import type { IDBPDatabase } from "idb";
import type { PastasSchema } from "..";

export class PastasList {
  // eslint-disable-next-line no-useless-constructor
  constructor(private readonly idb: IDBPDatabase<PastasSchema>) {}

  updateLastCopied(pasta: IDBMegaPasta) {
    return this.idb.put("list", {
      ...pasta,
      lastCopiedAt: Date.now(),
    });
  }

  getAllPastas() {
    return this.idb.transaction("list").store.getAll();
  }

  async addPasta(pasta: MegaPasta) {
    const pastaId = await this.idb
      .transaction("list", "readwrite")
      // @ts-expect-error id MUST be autogenerated by IndexedDB
      .store.add(pasta);
    return <IDBMegaPasta>{
      ...pasta,
      id: pastaId,
    };
  }
}
