import type { IDBPDatabase } from "idb";
import type { PastasSchema } from "..";

export class PastasListStore {
  constructor(private readonly idb: IDBPDatabase<PastasSchema>) {}

  put(pasta: IDBMegaPasta) {
    return this.idb.put("list", pasta);
  }

  getAll() {
    return this.idb.transaction("list").store.getAll();
  }

  add(pasta: MegaPasta) {
    // @ts-expect-error id MUST be autogenerated by IndexedDB
    return this.idb.transaction("list", "readwrite").store.add(pasta);
  }
}
