import { type DBSchema } from "idb";
import { emotesIdb } from "./emotes";
import type {
  IEmote,
  IEmoteCollection,
  IEmoteSet,
  IGlobalEmoteCollection,
} from "~/integrations";
import { emoteCollectionsIdb } from "~/client-only/IndexedDB/emote-collections";
import { pastasIdb } from "~/client-only/IndexedDB/pastas";

export type IndexedDBEmoteSet = Omit<IEmoteSet, "emotes"> & {
  emoteIds: IEmote["id"][];
};

export type IndexedDBEmoteCollection = Omit<IEmoteCollection, "sets"> & {
  sets: IndexedDBEmoteSet[];
};

export interface IndexedDBUserCollection {
  isActive: boolean;
  twitch: {
    nickname: string;
    id: number;
    username: Lowercase<IndexedDBUserCollection["twitch"]["nickname"]>;
  };
  updatedAt: number;
  collections: Record<
    "BetterTTV" /* | "Twitch" */ | "SevenTV" | "FrankerFaceZ",
    // FIXME: uncomment above when twitch api calls will be implemented
    IndexedDBEmoteCollection
  >;
  failedCollectionsReasons:
    | Record<"BetterTTV" | "SevenTV" | "FrankerFaceZ", string>
    | Record<string, never>;
}

export interface EmoteCollectionsSchema extends DBSchema {
  users: {
    key: IndexedDBUserCollection["twitch"]["username"];
    value: IndexedDBUserCollection;
  };
  global: {
    key: IGlobalEmoteCollection["source"];
    value: IGlobalEmoteCollection;
  };
}

export interface EmotesSchema {
  emotes: {
    key: [IEmote["id"], IEmote["source"]];
    value: IEmote & { updatedAt: number };
    indexes: {
      byId: IEmote["id"];
      bySource: "BetterTTV" | "SevenTV" | "FrankerFaceZ" | "Twitch";
      byToken: IEmote["token"];
      byTags: string[];
    };
  };
}

export interface PastasSchema extends DBSchema {
  list: {
    key: IDBMegaPasta["id"];
    // NOTE: actually it is IDBMegaPasta, but MegaPasta because of TypeScript yell
    // difference between IDBMegaPasta and MegaPasta that IDBMegaPasta has autogenerated id (by IndexedDB)
    value: MegaPasta;
    indexes: {
      byLength: IDBMegaPasta["length"];
      byCreatedAt: IDBMegaPasta["createdAt"];
      byText: IDBMegaPasta["text"];
      byTags: IDBMegaPasta["tags"];
      byValidTokens: IDBMegaPasta["validTokens"];
    };
  };
  bin: {
    key: IDBMegaPasta["id"];
    value: IDBMegaPasta;
  };
}

export const idb = {
  emoteCollections: emoteCollectionsIdb,
  emotes: emotesIdb,
  pastas: pastasIdb,
};

export { emoteCollectionsIdb, emotesIdb, pastasIdb };
