name: Run TODO to Issue

on: 
  pull_request:
    branches: main
  push: 
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: TODO to Issue
        uses: alstr/todo-to-issue-action@v5
        with:
          PROJECT: user/geforseN/pastbl
          PROJECTS_SECRET: ${{ secrets.TODO_TO_ISSUE_PROJECTS_SECRET }}
          INSERT_ISSUE_URLS: true
          CLOSE_ISSUES: true
      
      - name: Commit and Push Changes
        run: |
          git add -A
          if [[ `git status --porcelain` ]]; then
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git commit -m "chore: add issue links to TODOs"
            git push origin main
          else
            echo "No changes to commit"
          fi
