name: End-to-End Tests

on:
  deployment_status:

jobs:
  playwright:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'

    timeout-minutes: 5

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright Browsers
        run: pnpm install:playwright

      - name: Run Playwright tests on Vercel preview
        run: pnpm test:e2e
        if: ${{ github.event.deployment_status.environment == 'preview' }}
        env:
          PLAYWRIGHT_NUXT_HOST: ${{ github.event.deployment_status.environment_url }}

      - name: Run Playwright tests on Vercel production
        run: pnpm test:e2e
        if: ${{ github.event.deployment_status.environment == 'production' }}
        env:
          PLAYWRIGHT_NUXT_HOST: https://pastbl.vercel.app

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4.4.3
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
