name: Test Server API

on:
  deployment_status:
  push:
    branches:
      - main

jobs:
  tests:
    timeout-minutes: 5

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run dev server and Vitest on push to main
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: ./scripts/dev-vitest-nitro.sh
        env:
          HOST: 127.0.0.1
          PORT: 3000

      - name: Run server API tests on Vercel preview
        run: pnpm test:nitro
        if: ${{ github.event.deployment_status.environment == 'preview' }}
        env:
          VITEST_SERVER_API_BASE_URL: ${{ github.event.deployment_status.environment_url }}

      - name: Run server API tests on Vercel production
        run: pnpm test:nitro
        if: ${{ github.event.deployment_status.environment == 'production' }}
        env:
          VITEST_SERVER_API_BASE_URL: https://pastbl.vercel.app
