name: Playwright Tests

on:
  deployment_status:
jobs:
  vercel-preview-playwright:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
       
      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Run Playwright tests
        run: pnpm exec playwright test
        env:
          BASE_URL: ${{ github.event.deployment_status.environment_url }}
      
      - name: Upload Playwright report
        uses: actions/upload-artifact@v4.4.0
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
